on: 
  push:

name: CI build
jobs:
  build:
    name: CI build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.20

    - name: Build binaries
      run: go build -o dnscontrol-extended -ldflags "-s -w" -v .
      env:
        CGO_ENABLED: 0